<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>X from 26</title>
	<link rel="stylesheet" href="/stylesheets/main.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="X from 26 language game">
    <meta name="author" content="Zoltan Kalmar">
    <!-- Bootstrap core CSS -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">

	<script type="text/javascript" src="/javascripts/lib/zepto.min.js"></script>
	<script type="text/javascript" src="/javascripts/main.js"></script>
	<script type="text/javascript">window.onload = function() { Xfrom26_Init(window, $); }</script>
</head>
<body>
	<div class="container">
    <?php echo $this->layout()->content ?>
	</div>
</body>
</html>
