<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>X from 26</title>
	<link rel="stylesheet" href="/stylesheets/main.css" />
	<script type="text/javascript" src="/javascripts/lib/zepto.min.js"></script>
	<script type="text/javascript" src="/javascripts/main.js"></script>
	<script type="text/javascript">window.onload = function() { Xfrom26_Init(window, $); }</script>
</head>
<body>
    <?php echo $this->layout()->content ?>
</body>
</html>
